language: python
python:
    - "3.6.8"  # last bugfix release, end-of-life in 2021
    - "3.7.8"  # last bugfix release, end-of-life in 2023
    - "3.8"
    - "3.9"
    - "3.10-dev"
install:
    - pip install coveralls
    - pip install tox
script:
    # run tests with coverage
    - tox
after_success:
    # upload reports to coveralls.io
    - coveralls
