language: python
python:
    - "3.6.13"
    - "3.7.10"
    - "3.8.8"
    - "3.9.2"
    - "3.10"
install:
    - pip install coveralls
    - pip install tox
script:
    # run tests with coverage
    - tox
after_success:
    # upload reports to coveralls.io
    - coveralls
